# Steps for building the app using GCP Cloud Build, triggered by GitHub web hooks.
steps:
- name: node:20.11.0
  entrypoint: npm
  args: ["install"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"
